version: '3.9'

services:
  nestjs_api_prod:
    # image: nestjs-docker
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
     - PORT=9000
     - NODE_ENV=production
    # mapping from the host port to the container port
    ports:
      - "9000:9000"  
    volumes:
      - ./src/usr/src/app/src

mysql_db:
     image: mysql
     ports:  
       - "3306:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=mysql
       - MYSQL_DATABASE=mysql
       - MYSQL_USER=mysql
       - MYSQL_PASSWORD=mysql
       - MYSQL_TCP_PORT=3306